name: Conditionals Workflow

on:
 push:
   branches:
     - main
     
 pull_request:
   branches:
     - main
     
 workflow_dispatch:
    
jobs:
  conditional-steps:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print branch information
        run: |
          echo "Branch ref is: ${{ github.ref }}"
          echo "Event name is: ${{ github.event_name }}"

      - name: Run only on main branch
        if: github.ref == 'refs/heads/main'
        run: echo "This step runs only on the main branch"
        
      - name: This step will fail but workflow continues
        id: fail-step
        continue-on-error: true
        run: |
          echo "This step is intentionally failing"
          exit 1

      - name: Run only if fail-step failed
        if: steps.fail-step.outcome == 'failure'
        run: echo "The fail-step failed, so this step is running"

      - name: Final step
        run: echo "Workflow continued after failure because continue-on-error was true"
        
  push-only-job:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    
    steps:
      - name: This job runs only on push events
        run: |
          echo: "This job runs only when event is push"
          echo: "Current event is: ${{ github.evnt_name }}"
  
