name: Docker Build and Push CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Get short commit SHA
        id: vars
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Check Docker secrets
        run: |
          if [ -n "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "Docker username is set"
          else
            echo "Docker username is missing"
            exit 1
          fi

          if [ -n "${{ secrets.DOCKER_TOKEN }}" ]; then
            echo "Docker token is set"
          else
            echo "Docker token is missing"
            exit 1
          fi

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login \
            --username "${{ secrets.DOCKER_USERNAME }}" \
            --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/day45-docker-app:latest \
            -t ${{ secrets.DOCKER_USERNAME }}/day45-docker-app:sha-${{ steps.vars.outputs.SHORT_SHA }} \
            .

      - name: Push Docker image tags
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/day45-docker-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/day45-docker-app:sha-${{ steps.vars.outputs.SHORT_SHA }}