# Workflow name shown in the GitHub Actions tab 

name: Hello Workflow

# This workflow will run every time you push code from main branch to the remote repository

on:
  push:
    branches:
      - main

# jobs define the work GitHub Actions will perform

jobs:
  greet:      # job name
    runs-on: ubuntu-latest # The job will run on a fresh Ubuntu Linux virtual machine


    steps: # Steps are the individual actions/commands inside the job
      - name: Chek out the code  # Step 1: Download/checkout your repository code into the runner
        uses: actions/checkout@v4

      - name: Print Hello message  # Step 2: Run a shell command to print a message
        run: echo "Hello from GitHub Actions!!"

      - name: Print current date and time
        run: date

      - name: Print branch name commit ID
        run: |
          echo "Branch name is ${{ github.ref_name }}"
          echo "Commit ID is ${{ github.sha }}"
          echo "Short Commit ID is ${GITHUB_SHA::7}"

      - name: List files in repository
        run: ls -la

      - name: Print runner operating system
        run: echo "Runner operating system is ${{ runner.os }}"
 


          