name: PR Lifecycle Events d47-t1

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
      
jobs:
  pr-info:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print PR event action
        run: | 
          echo "PR event action: ${{ github.event.action }}"
        
      - name: Print PR title
        run: | 
          echo "PR title: ${{ github.event.pull_request.title }}"

      - name: Print source and target branches 
        run: |
          echo "Source branch: ${{ github.event.pull_request.head.ref }}"
          echo "Target branch: ${{ github.event.pull_request.base.ref }}"

      - name: Run only when PR is merged
        run: |
          echo "This pull request was merged."
          echo "Merged by: ${{ github.event.pull_request.merged_by.login }}"
    



        
        