name: Scheduled Trigger

on:
  schedule:
    - cron: '5 * * * *' 
  workflow_dispatch:
jobs:
  scheduled-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print scheduled workflow message
        run: |
          echo "This workflow runs every day at midnight UTC"
          echo "Current date and time:" ; date
