name: Secrets Demo

on:
  push:

  workflow_dispatch:
    
jobs:
  check-secert:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check if secret is set
        run: |
          if [ -n "${{ secrets.MY_SECRET_MESSAGE }}" ]; then
            echo "The secret is set: true"
          else
            echo "The secret is set: false"
          fi
          
      - name: Try to print secret directly
        run: |
          echo "Trying to print secret:"
          echo "${{ secrets.MY_SECRET_MESSAGE }}"
